/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProposalRouteImport } from './routes/proposal'
import { Route as ProposalSentRouteImport } from './routes/proposal-sent'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalRoute = ProposalRouteImport.update({
  id: '/proposal',
  path: '/proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalSentRoute = ProposalSentRouteImport.update({
  id: '/proposal-sent',
  path: '/proposal-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/camera': typeof CameraRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/proposal': typeof ProposalRoute
  '/proposal-sent': typeof ProposalSentRoute
  '/review': typeof ReviewRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/camera': typeof CameraRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/proposal': typeof ProposalRoute
  '/proposal-sent': typeof ProposalSentRoute
  '/review': typeof ReviewRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads': typeof LeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/camera': typeof CameraRoute
  '/explore': typeof ExploreRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/proposal': typeof ProposalRoute
  '/proposal-sent': typeof ProposalSentRoute
  '/review': typeof ReviewRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/camera'
    | '/explore'
    | '/pricing'
    | '/profile'
    | '/proposal'
    | '/proposal-sent'
    | '/review'
    | '/leads/$id'
    | '/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/camera'
    | '/explore'
    | '/pricing'
    | '/profile'
    | '/proposal'
    | '/proposal-sent'
    | '/review'
    | '/leads/$id'
    | '/leads'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/camera'
    | '/explore'
    | '/pricing'
    | '/profile'
    | '/proposal'
    | '/proposal-sent'
    | '/review'
    | '/leads/$id'
    | '/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  CameraRoute: typeof CameraRoute
  ExploreRoute: typeof ExploreRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProposalRoute: typeof ProposalRoute
  ProposalSentRoute: typeof ProposalSentRoute
  ReviewRoute: typeof ReviewRoute
  LeadsIdRoute: typeof LeadsIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal': {
      id: '/proposal'
      path: '/proposal'
      fullPath: '/proposal'
      preLoaderRoute: typeof ProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal-sent': {
      id: '/proposal-sent'
      path: '/proposal-sent'
      fullPath: '/proposal-sent'
      preLoaderRoute: typeof ProposalSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  CameraRoute: CameraRoute,
  ExploreRoute: ExploreRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProposalRoute: ProposalRoute,
  ProposalSentRoute: ProposalSentRoute,
  ReviewRoute: ReviewRoute,
  LeadsIdRoute: LeadsIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
